# Generated by Django 3.0.7 on 2020-06-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('slotKey', models.CharField(max_length=100)),
                ('bookingKey', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('pitch', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('sumittedDate', models.DateTimeField()),
            ],
        ),
    ]
